import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

const work = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${work.className} bg-white text-black`}>
        {children}
      </body>
    </html>
  );
}
